import { join } from 'path'
import { pathToFileURL } from 'url'

import type { ContentBlock } from '@agentclientprotocol/sdk'
import type { App, Vault } from 'obsidian'

import type { ChatSessionState } from '../types/chat'

export const DEFAULT_CHAT_LOG_FOLDER = 'YOLO'

const DEFAULT_CHAT_LOG_FILE = `${DEFAULT_CHAT_LOG_FOLDER}/untitled.md`

const FALLBACK_FILE_NAME = 'untitled'

const MAX_FILE_NAME_LENGTH = 80

const AUTO_GENERATED_COMMENT =
  '<!-- Auto-generated by OpenYOLO. Will be overwritten on next save. -->'

const SESSION_MARKER = '<!-- openyolo-session: '

const writeQueues = new WeakMap<Vault, Promise<void>>()

export type ConversationLogInfo = {
  /** 库内相对路径 */
  path: string
  /** 不含扩展名的文件名（即保存时的对话标题） */
  name: string
  mtime: number
}

/**
 * 归一化库内相对路径：去掉首尾空白与斜杠、折叠空段与 "."，含 ".." 时回退默认
 * 路径，避免 adapter 写入逃逸出 vault。
 */
export function normalizeChatLogPath(raw: string): string {
  const trimmed = raw.trim().replace(/^\/+|\/+$/g, '')
  if (!trimmed) return DEFAULT_CHAT_LOG_FILE
  const segments = trimmed
    .split('/')
    .filter((segment) => segment && segment !== '.')
  if (segments.some((segment) => segment === '..')) return DEFAULT_CHAT_LOG_FILE
  return segments.join('/')
}

/** 归一化保存对话记录的库内文件夹路径。 */
export function normalizeChatLogFolder(raw: string): string {
  const trimmed = raw.trim().replace(/^\/+|\/+$/g, '')
  if (!trimmed) return DEFAULT_CHAT_LOG_FOLDER
  const segments = trimmed
    .split('/')
    .filter((segment) => segment && segment !== '.')
  if (segments.some((segment) => segment === '..'))
    return DEFAULT_CHAT_LOG_FOLDER
  return segments.join('/')
}

/**
 * 把对话标题转成安全的文件名：剔除文件系统保留字符与控制字符、压缩空白、
 * 去掉首尾句点并截断；空标题回退为 untitled。
 */
export function sanitizeChatLogFileName(title: string): string {
  const withoutReserved = title.replace(/[\\/:*?"<>|]/g, ' ')
  let withoutControl = ''
  for (const char of withoutReserved) {
    withoutControl += char < ' ' ? ' ' : char
  }
  const cleaned = withoutControl
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^\.+|\.+$/g, '')
    .slice(0, MAX_FILE_NAME_LENGTH)
    .trim()
  return cleaned || FALLBACK_FILE_NAME
}

/** 当天日期子文件夹名，格式 YYYY-MM-DD（本地时区）。 */
export function chatLogDateFolder(date: Date = new Date()): string {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

/** 保存路径 = <文件夹>/<当天日期>/<对话标题>.md；标题相同的会话同一天覆盖同一个文件。 */
export function chatLogFilePath(
  folder: string,
  title: string,
  date: Date = new Date(),
): string {
  return `${normalizeChatLogFolder(folder)}/${chatLogDateFolder(date)}/${sanitizeChatLogFileName(title)}.md`
}

/**
 * 把时间线中的用户/助手文本序列化为 Markdown；跳过工具调用与空消息。
 * 返回空串表示没有可保存的内容。
 */
export function serializeConversation(state: ChatSessionState): string {
  const sections: string[] = []
  for (const entry of state.entries) {
    if (entry.kind !== 'user' && entry.kind !== 'assistant') continue
    const text = entry.text.trim()
    if (!text) continue
    sections.push(
      `## ${entry.kind === 'user' ? 'User' : 'Assistant'}\n\n${text}`,
    )
  }
  if (sections.length === 0) return ''

  const header = [AUTO_GENERATED_COMMENT]
  if (state.sessionId) {
    header.push(`<!-- openyolo-session: ${state.sessionId} -->`)
  }
  header.push(
    '',
    '# OpenYOLO conversation history',
    '',
    '> This file contains AI chat history saved by the OpenYOLO plugin.',
    '> 本文件由 OpenYOLO 插件保存，内容是与 AI 的历史对话记录。',
    '',
    `- Session: ${state.title.trim() || 'untitled'}`,
    `- Updated: ${new Date().toISOString()}`,
  )
  return `${header.join('\n')}\n\n${sections.join('\n\n')}\n`
}

/** 从笔记内容中解析保存时写入的会话 id 标记；没有标记时返回 null。 */
export function extractSessionId(content: string): string | null {
  const start = content.indexOf(SESSION_MARKER)
  if (start === -1) return null
  const idStart = start + SESSION_MARKER.length
  const end = content.indexOf('-->', idStart)
  if (end === -1) return null
  const id = content.slice(idStart, end).trim()
  return id || null
}

/** 会话 id 的短后缀，用于同名笔记冲突时区分文件。 */
export function shortSessionId(sessionId: string): string {
  const alnum = sessionId.replace(/[^a-zA-Z0-9]/g, '')
  return alnum.slice(-8) || sessionId
}

async function ensureParentFolders(vault: Vault, path: string): Promise<void> {
  const segments = path.split('/')
  segments.pop()
  let current = ''
  for (const segment of segments) {
    current = current ? `${current}/${segment}` : segment
    if (!vault.getAbstractFileByPath(current)) {
      await vault.createFolder(current)
    }
  }
}

async function processChatLog(
  vault: Vault,
  path: string,
  content: string,
): Promise<void> {
  await ensureParentFolders(vault, path)
  const file = vault.getFileByPath(path)
  if (file) {
    await vault.process(file, () => content)
    return
  }
  const occupied = vault.getAbstractFileByPath(path)
  if (occupied) {
    throw new Error(`${path} exists but is not a file`)
  }
  try {
    await vault.create(path, content)
  } catch (error) {
    const raced = vault.getFileByPath(path)
    if (!raced) throw error
    await vault.process(raced, () => content)
  }
}

/** 串行化本插件对每个 vault 的覆盖写，避免与其他写入方交错。 */
export function writeConversationLog(
  app: App,
  path: string,
  content: string,
): Promise<void> {
  const vault = app.vault
  const normalized = normalizeChatLogPath(path)
  const previous = writeQueues.get(vault) ?? Promise.resolve()
  const current = previous
    .catch(() => undefined)
    .then(() => processChatLog(vault, normalized, content))
  writeQueues.set(vault, current)
  return current.finally(() => {
    if (writeQueues.get(vault) === current) writeQueues.delete(vault)
  })
}

/** 列出记录文件夹（含日期子文件夹）下所有已保存的对话笔记，按 mtime 倒序；文件夹不存在时返回空。 */
export async function listConversationLogs(
  app: App,
  folder: string,
): Promise<ConversationLogInfo[]> {
  const normalized = normalizeChatLogFolder(folder)
  const adapter = app.vault.adapter
  let root: { files: string[]; folders: string[] }
  try {
    root = await adapter.list(normalized)
  } catch {
    return []
  }
  const candidates = root.files.filter((path) => path.endsWith('.md'))
  for (const subFolder of root.folders) {
    try {
      const listed = await adapter.list(subFolder)
      candidates.push(...listed.files.filter((path) => path.endsWith('.md')))
    } catch {
      continue
    }
  }
  const logs: ConversationLogInfo[] = []
  for (const path of candidates) {
    const stat = await adapter.stat(path)
    if (stat?.type !== 'file') continue
    const name = (path.split('/').pop() ?? path).replace(/\.md$/, '')
    logs.push({ path, name, mtime: stat.mtime })
  }
  logs.sort((left, right) => right.mtime - left.mtime)
  return logs
}

/** 在记录文件夹中查找包含指定会话 id 标记的笔记路径。 */
export async function findConversationLogBySessionId(
  app: App,
  folder: string,
  sessionId: string,
): Promise<string | null> {
  const logs = await listConversationLogs(app, folder)
  for (const log of logs) {
    try {
      const content = await app.vault.adapter.read(log.path)
      if (extractSessionId(content) === sessionId) return log.path
    } catch {
      continue
    }
  }
  return null
}

/**
 * 保存对话：优先按会话 id 覆盖已有笔记（标题变更也不产生新文件）；
 * 否则写入 <文件夹>/<当天日期>/<标题>.md，同名冲突时追加 id 短后缀。
 * 返回写入的路径；没有可保存内容时返回 null。
 */
export async function saveConversationLog(
  app: App,
  folder: string,
  state: ChatSessionState,
  date: Date = new Date(),
): Promise<string | null> {
  const content = serializeConversation(state)
  if (!content) return null

  const sessionId = state.sessionId
  if (sessionId) {
    const existing = await findConversationLogBySessionId(
      app,
      folder,
      sessionId,
    )
    if (existing) {
      await writeConversationLog(app, existing, content)
      return existing
    }
  }

  let path = chatLogFilePath(folder, state.title, date)
  if (sessionId && app.vault.getAbstractFileByPath(path)) {
    path = chatLogFilePath(
      folder,
      `${state.title.trim() || 'untitled'}-${shortSessionId(sessionId)}`,
      date,
    )
  }
  await writeConversationLog(app, path, content)
  return path
}

export function vaultBasePath(app: App): string {
  const adapter = app.vault.adapter as { getBasePath?: () => string }
  return typeof adapter.getBasePath === 'function' ? adapter.getBasePath() : ''
}

/**
 * 构建“恢复历史对话”提示：text 为固定指令模板，笔记内容以嵌入式
 * resource 块（text/plain）直接随提示词发送——resource_link 只会被
 * opencode 当作文件引用，模型需要自行搜索而无法定位到指定笔记。
 */
export function buildRestoreBlocks(
  text: string,
  noteText: string,
  notePath: string,
  basePath: string,
): ContentBlock[] {
  const normalized = normalizeChatLogPath(notePath)
  const absolutePath = basePath ? join(basePath, normalized) : normalized
  return [
    { type: 'text', text },
    {
      type: 'resource',
      resource: {
        uri: pathToFileURL(absolutePath).href,
        mimeType: 'text/plain',
        text: noteText,
      },
    },
  ]
}
